apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  selector:
    app: mongodb
  # Giữ ClusterIP để chỉ có K8s nội bộ mới gọi được DB này
  type: ClusterIP
