version: '3.8'

services:
  # 1. source db
  postgres-source:
    image: postgres:13
    container_name: postgres-source
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sales_db
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "wal_level=logical"] # cho phep postgre ghi lai lich su thay doi du lieu theo cach ma Debezium co the doc duoc de day vao Kafka
    deploy:
      resources:
        limits:
          memory: 512M # gioi han ram

  # 2. Quản lý Kafka (Zookeeper)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # 3. Trung chuyen data bang kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # ------------------------------------
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    deploy:
      resources:
        limits:
          memory: 1G 

  # 4. ket noi postgres voi kafka
  debezium:
    image: debezium/connect:2.4
    container_name: debezium-connect
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
      - kafka
      - postgres-source

  # 5. Data Lake (MinIO)
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console UI
    environment:
      - MINIO_ROOT_USER=minio_user
      - MINIO_ROOT_PASSWORD=minio_password
    command: server /data --console-address ":9001"

  # 6. Kho dữ liệu đích (Warehouse)
  postgres-warehouse:
    image: postgres:13
    container_name: postgres-warehouse
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=warehouse_db
    ports:
      - "5433:5432" # tranh trung' cong voi src