apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  serviceName: "kafka"
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      enableServiceLinks: false
      initContainers:
        - name: wait-for-zookeeper
          image: busybox
          command: ['sh', '-c', 'until nc -z zookeeper.default.svc.cluster.local 2181; do echo waiting for zookeeper; sleep 2; done;']
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 9092
              name: external
            - containerPort: 9094
              name: internal
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper.default.svc.cluster.local:2181"
            
            # 1. Định nghĩa các cổng lắng nghe
            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:9094,EXTERNAL://0.0.0.0:9092"
            
            # 2. Quan trọng: Quảng bá địa chỉ để Java và Debezium kết nối được
            # Cổng 9092 dành cho máy Mac (localhost) qua port-forward
            # Cổng 9094 dành cho các Service khác TRONG K8S (như Debezium, Spark)
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka.default.svc.cluster.local:9094,EXTERNAL://localhost:9092"
            
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "168"
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi