apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
      name: external # Để host có thể gửi log Event vào Kafka
      nodePort: 30092
    - port: 9094
      targetPort: 9094
      name: internal # Để Pod khác trong cụm như UI gọi vào
  selector:
    app: kafka
