spring:
  # 1. Setup PostgreSQL
  datasource:
    url: jdbc:postgresql://100.126.251.93:5432/olist_db
    username: dongthe04
    password: "123456"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # 2. Setup MongoDB
  data:
    mongodb:
      uri: mongodb://localhost:27017/bigdata_db

  # 3. Setup Kafka
  kafka:
    bootstrap-servers: 100.126.251.93:9092
    consumer:
      group-id: olist-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

# ĐƯA MINIO RA NGOÀI CÙNG NHƯ THẾ NÀY
minio:
  # Dùng port 9000 để code giao tiếp.
  url: http://100.126.251.93:9000
  access-key: admin
  secret-key: password123
  bucket: olist-lakehouse

# 4. Setup Server
server:
  port: 8081

# 5. Setup Logging
logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG
    org.springframework.kafka: INFO

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false