spring:
  # 1. Setup PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/olist
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        jdbc:
          time_zone: UTC

  jackson:
    time_zone: UTC
  # 2. Setup MongoDB
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/olist_db

  # 3. Setup Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: olist-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      acks: all
      retries: 3

      properties:
        enable.idempotence: true
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# 4.Setup Server
server:
  port: 8082

# 5. SetupLogging
logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG
    org.springframework.kafka: INFO

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: password123
  bucket: olist-lakehouse
